### ISSUE TITLE
Crash in empty standard payment card form

### ISSUE THREAD

**Issue by ValeryBoretsky** [cloudpayments/CloudPayments-SDK-Android#5]
Crash when press on button pay on standard payment form with empty card number.
Release 1.1.7

```
java.lang.StringIndexOutOfBoundsException: length=0; index=4
    at java.lang.String.substring(String.java:2060)
    at ru.cloudpayments.sdk.card.Card$Companion.isUzcardCard(Unknown Source:4)
    at ru.cloudpayments.sdk.card.Card$Companion.isValidCvv(Unknown Source:17)
    at ru.cloudpayments.sdk.ui.dialogs.PaymentCardFragment.isValid(Unknown Source:52)
    at ru.cloudpayments.sdk.ui.dialogs.PaymentCardFragment.onViewCreated$lambda-6(Unknown Source:101)
    at ru.cloudpayments.sdk.ui.dialogs.PaymentCardFragment.$r8$lambda$GzmXnnbKvYRGXYjQjrxbmpQGFCk(Unknown Source:0)
    at ru.cloudpayments.sdk.ui.dialogs.PaymentCardFragment$$ExternalSyntheticLambda6.onClick(Unknown Source:2)
    at android.view.View.performClick(View.java:7297)
    at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1219)
    at android.view.View.performClickInternal(View.java:7274)
    at android.view.View.access$3600(View.java:819)
    at android.view.View$PerformClick.run(View.java:28017)
    at android.os.Handler.handleCallback(Handler.java:914)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:225)
    at android.app.ActivityThread.main(ActivityThread.java:7564)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by a-ignatov-cp** [comment]
Thanks, fixed
Please use version 1.1.9
